- name: Recovery banyak VM dari backup Proxmox otomatis tanpa pause
  hosts: proxmox
  gather_facts: no
  vars:
    proxmox_host: "10.91.0.184"
    proxmox_port: "8006"
    username: "root@pam"
    password: "nadnin123"
    storage_target: "local-lvm"
    backup_files: []
    new_vmids: []

  tasks:
    - name: Login ke Proxmox untuk dapat Ticket & CSRF Token
      uri:
        url: "https://{{ proxmox_host }}:{{ proxmox_port }}/api2/json/access/ticket"
        method: POST
        validate_certs: no
        body_format: form-urlencoded
        body:
          username: "{{ username }}"
          password: "{{ password }}"
      register: login_response

    - name: Set cookie dan CSRF token
      set_fact:
        pve_ticket: "{{ login_response.json.data.ticket }}"
        csrf_token: "{{ login_response.json.data.CSRFPreventionToken }}"

    - name: Bikin kombinasi backup file dan vmid
      set_fact:
        restore_items: "{{ restore_items | default([]) + [ {'archive': item.0, 'vmid': item.1} ] }}"
      with_together:
        - "{{ backup_files }}"
        - "{{ new_vmids }}"

    - name: Jalankan restore untuk setiap backup
      loop: "{{ restore_items }}"
      vars:
        archive_name: "{{ item.archive }}"
        vmid_restore: "{{ item.vmid }}"
      uri:
        url: "https://{{ proxmox_host }}:{{ proxmox_port }}/api2/json/nodes/nadnin/qemu"
        method: POST
        headers:
          Cookie: "PVEAuthCookie={{ pve_ticket }}"
          CSRFPreventionToken: "{{ csrf_token }}"
        validate_certs: no
        body_format: form-urlencoded
        body:
          vmid: "{{ vmid_restore }}"
          archive: "local:{{ archive_name }}"
          storage: "{{ storage_target }}"
          force: 1
      register: restore_response
      loop_control:
        label: "{{ archive_name }}"

    - name: Tampilkan hasil restore
      debug:
        msg: "Task Restore: {{ restore_response.results | map(attribute='json.data') | list }}"
